### PR TITLE
Upgrade dependencies to solve security issue

### PR DESCRIPTION
**Pull request by exos**
Upgrade dependencies to solve a high security issue:

```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimatch                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ glob                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ glob > minimatch                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/118                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

More info: https://npmjs.com/advisories/118

Please apply this PR asap.

### CODE REVIEW

**Comment by cpsubrian** [comment]
@srijs Is maintaining this now. I added you, @exos as a collaborator to this repo. I'll let @srijs decide if he wants to give you npm publishing access.

**Comment by cpsubrian** [comment]
Side note: I noticed that there is a fork of this on npm now as `node-etc`. Wonder if ya'll should merge?

**Comment by exos** [comment]
> @srijs Is maintaining this now. I added you, @exos as a collaborator to this repo. I'll let @srijs decide if he wants to give you npm publishing access.

Thank you for the role, I'm using this package in several projects, so I am interested that it is updated. What would be the next step? merge my changes or wait for approval of @srijs? 

> Side note: I noticed that there is a fork of this on npm now as `node-etc`. Wonder if ya'll should merge?

Reading about `node-etc` package, it's not a fork of this project, but:

> Inspired by cpsubrian/node-etc

I think this package has the necessary just to work as a configuration provider and it's ok.

**Comment by cpsubrian** [comment]
I’ll give @srijs a day or two to respond here and if he doesn’t I’ll give
you npm publishing permission and you can merge and publish as you wish.

**Comment by exos** [comment]
Merged :)

**Pull request merged**
